### ISSUE TITLE
E-Mail notifications of issues

### ISSUE THREAD

**Issue by joakee** [QuickRecon/ScotchOARKit#19]
We need to disable it. Its driving me mentall.

**Comment by TomW1605** [comment]
u can disable it in your notification settings. it is a personal setting not a global

**Comment by QuickRecon** [comment]
Disable it it githubs settings

**Comment by Moulberry** [comment]
Your spelling is driving me mentall.

**Comment by joakee** [comment]
it was a typo

**Comment by joakee** [comment]
and campbell told me that they can be globally disabled

**Comment by TomW1605** [comment]
yes but is dosent anoy me nd i use it

**Comment by QuickRecon** [comment]
I'm not disabling it globally as I have go into a folder and like it for record keeping.

**Comment by joakee** [comment]
How did you direct them to a folder? (I barely use E-mail)

**Comment by QuickRecon** [comment]
folder rules, google it.

**Comment by joakee** [comment]
If only these GitHub email things had IRC support. I like IRC.

**Comment by TomW1605** [comment]
i can show u at lunch while aran is showing me how to view the wip branch in intelij

**Comment by joakee** [comment]
What, IRC support?!

...or email?

**Comment by TomW1605** [comment]
No email rules I typed it befor I saw your respons

---

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have or believe you may have received this email in error please notify the sender immediately and delete this email from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited. The views or opinions presented in this email are solely those of the author or sender and do not necessarily represent those of Scotch College. It is the responsibility of the recipient to check this email and any attachments for the presence of viruses. Scotch College accepts no liability for any damage caused by any virus transmitted by this email.
